SELECT CURTIME();
SELECT CURDATE();
SELECT DAYOFWEEK(CURDATE());
SELECT DAYNAME(CURDATE());
SELECT DAYNAME(NOW());
SELECT DATE_FORMAT(CURDATE(), '%m/%d/%Y');
SELECT DATE_FORMAT(NOW(), '%M %D at %k:%i');
CREATE TABLE tweets (
	content VARCHAR(150), 
    time_created DATETIME DEFAULT NOW()
);
INSERT INTO tweets (content)
VALUES('Hello World');
SELECT * FROM tweets;